language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - pip install -r test_requirements.txt
script:
  - python setup.py test
